image: java:11

stages:
  - build
  - docker-build
  - docker-push
  - docker-deploy-swarm

before_script:
  - chmod +x gradlew

build:
  stage: build
  script: ./gradlew clean build
  artifacts:
    paths:
      - build/libs/socshared-system-statistic-service-1.0.0-SNAPSHOT.jar
    expire_in: 1 hrs

docker-build:
  stage: docker-build
  script:
    - docker build -t $CI_DOCKER_LOGIN/socshared-system-statistic-service .

docker-push:
  stage: docker-push
  script:
    - docker login -u "$CI_DOCKER_LOGIN" -p "$CI_DOCKER_PASSWORD"
    - docker push $CI_DOCKER_LOGIN/socshared-system-statistic-service

docker-deploy-swarm:
  stage: docker-deploy-swarm
  script:
    - touch .env_stat
    - echo "SPRING_PROFILE=$SPRING_PROFILE" >> .env_stat
    - echo "SENTRY_API_KEY=$SENTRY_API_KEY" >> .env_stat
    - echo "SENTRY_URL=$SENTRY_URL" >> .env_stat
    - echo "SECRET_JWT_KEY=$SECRET_JWT_KEY" >> .env_stat
    - echo "SERVICE_ID=$SERVICE_ID" >> .env_stat
    - echo "AUTH_SERVICE=$AUTH_SERVICE" >> .env_stat
    - docker stack deploy -c docker-compose.yaml socshared
