spring:
  zipkin:
    base-url: http://zipkin:9411/
    service:
      name: ${spring.application.name}
  main:
    allow-bean-definition-overriding: true

sentry:
  api:
    key: ${SENTRY_API_KEY:8a102d3eae46498f9e1c5db42298308bbf50051724ae4cac9ee86b13ea9dfbbd}
  url: ${SENTRY_URL:https://sentry.socshared.ml}

feign:
  url:
    auth: ${AUTH_SERVICE:http://auth-service:9999/}

management:
  endpoints:
    web:
      exposure:
        include: auditevents, beans, caches, conditions, configprops, health, httptrace, info, loggers, metrics, mappings, shutdown
